### ISSUE TITLE
Variable definition bug in 404 error handler

### ISSUE THREAD

**Issue by rezib** [rackslab/Fatbuildr#126]
The following error has been seen thrown when 404 error handler is raised in Fatbuildrweb:

```
uwsgi[20397]: uWSGIWorker4Core0: [ERROR] Exception on /devs/ [GET]
uwsgi[20397]: Traceback (most recent call last):
uwsgi[20397]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
uwsgi[20397]:     rv = self.dispatch_request()
uwsgi[20397]:          ^^^^^^^^^^^^^^^^^^^^^^^
uwsgi[20397]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1785, in dispatch_request
uwsgi[20397]:     self.raise_routing_exception(req)
uwsgi[20397]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1767, in raise_routing_exception
uwsgi[20397]:     raise request.routing_exception  # type: ignore
uwsgi[20397]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi[20397]:   File "/usr/lib/python3/dist-packages/flask/ctx.py", line 351, in match_request
uwsgi[20397]:     result = self.url_adapter.match(return_rule=True)  # type: ignore
uwsgi[20397]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi[20397]:   File "/usr/lib/python3/dist-packages/werkzeug/routing/map.py", line 624, in match
uwsgi[20397]:     raise NotFound() from None
uwsgi[20397]: werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
uwsgi[20397]: During handling of the above exception, another exception occurred:
uwsgi[20397]: Traceback (most recent call last):
uwsgi[20397]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
uwsgi[20397]:     response = self.full_dispatch_request()
uwsgi[20397]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi[20397]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
uwsgi[20397]:     rv = self.handle_user_exception(e)
uwsgi[20397]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi[20397]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1666, in handle_user_exception
uwsgi[20397]:     return self.handle_http_exception(e)
uwsgi[20397]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi[20397]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1606, in handle_http_exception
uwsgi[20397]:     return self.ensure_sync(handler)(e)
uwsgi[20397]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi[20397]:   File "/usr/lib/python3/dist-packages/fatbuildr/protocols/http/server/views.py", line 66, in error_not_found
uwsgi[20397]:     if 'output' in request.view_args and request.view_args['output'] == 'html':
uwsgi[20397]:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi[20397]: TypeError: argument of type 'NoneType' is not iterable
```

**Comment by rezib** [comment]
According to [Flask documentation](https://flask.palletsprojects.com/en/2.3.x/api/#flask.Request.view_args), `request.view_args` can happen to be None when an exception occurs when matching.
