### ISSUE TITLE
Missing dependency on patch command

### ISSUE THREAD

**Issue by rezib** [rackslab/Fatbuildr#145]
On a fresh installation, build can fail on this error:

```
fatbuildrd[420317]: worker-devs: [INFO] Applying patch generic/0001-replace-version
fatbuildrd[420317]: Exception in thread worker-devs:
fatbuildrd[420317]: Traceback (most recent call last):
fatbuildrd[420317]:   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
fatbuildrd[420317]:     self.run()
fatbuildrd[420317]:   File "/usr/lib/python3.11/threading.py", line 975, in run
fatbuildrd[420317]:     self._target(*self._args, **self._kwargs)
fatbuildrd[420317]:   File "/usr/lib/python3/dist-packages/fatbuildr/cli/fatbuildrd.py", line 133, in _worker
fatbuildrd[420317]:     instance.tasks_mgr.run(task)
fatbuildrd[420317]:   File "/usr/lib/python3/dist-packages/fatbuildr/tasks/manager.py", line 178, in run
fatbuildrd[420317]:     task.run()
fatbuildrd[420317]:   File "/usr/lib/python3/dist-packages/fatbuildr/builds/__init__.py", line 226, in run
fatbuildrd[420317]:     self.prepare()
fatbuildrd[420317]:   File "/usr/lib/python3/dist-packages/fatbuildr/builds/__init__.py", line 343, in prepare
fatbuildrd[420317]:     self.supplementary_archives_symlinks_patch()
fatbuildrd[420317]:   File "/usr/lib/python3/dist-packages/fatbuildr/builds/__init__.py", line 457, in supplementary_archives_symlinks_patch
fatbuildrd[420317]:     (upstream_dir, archive_subdir, git) = self._prepare_git_build_tree()
fatbuildrd[420317]:                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fatbuildrd[420317]:   File "/usr/lib/python3/dist-packages/fatbuildr/builds/__init__.py", line 427, in _prepare_git_build_tree
fatbuildrd[420317]:     git.import_patches(self.patches_dir)
fatbuildrd[420317]:   File "/usr/lib/python3/dist-packages/fatbuildr/git.py", line 256, in import_patches
fatbuildrd[420317]:     self._import_patches_subdir(patches_subdir)
fatbuildrd[420317]:   File "/usr/lib/python3/dist-packages/fatbuildr/git.py", line 267, in _import_patches_subdir
fatbuildrd[420317]:     self._apply_patch(patch)
fatbuildrd[420317]:   File "/usr/lib/python3/dist-packages/fatbuildr/git.py", line 312, in _apply_patch
fatbuildrd[420317]:     subprocess.run(cmd, input=patch.content, cwd=self.path)
fatbuildrd[420317]:   File "/usr/lib/python3.11/subprocess.py", line 548, in run
fatbuildrd[420317]:     with Popen(*popenargs, **kwargs) as process:
fatbuildrd[420317]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
fatbuildrd[420317]:   File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
fatbuildrd[420317]:     self._execute_child(args, executable, preexec_fn, close_fds,
fatbuildrd[420317]:   File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
fatbuildrd[420317]:     raise child_exception_type(errno_num, err_msg, err_filename)
fatbuildrd[420317]: FileNotFoundError: [Errno 2] No such file or directory: 'patch'
fatbuildrd[420317]: timer: [WARNING] Detected dead worker-devs thread, notifying service manager
systemd[1]: fatbuildrd.service: Watchdog request (last status: Worker thread worker-devs failed)!
systemd[1]: fatbuildrd.service: Killing process 420317 (fatbuildrd) with signal SIGABRT.
```

This is due to a missing dependency on `patch` command.

**Comment by rezib** [comment]
Fixed with 2cec923.
