### ISSUE TITLE
Key error with `fatbuildrctl list` on REST API

### ISSUE THREAD

**Issue by rezib** [rackslab/Fatbuildr#178]
```
$ echo $FATBUILDR_URI
https://build.rackslab.io/devs
$ fatbuildrctl list
Traceback (most recent call last):
  File "/usr/bin/fatbuildrctl", line 33, in <module>
    sys.exit(load_entry_point('Fatbuildr==2.1.0.dev230', 'console_scripts', 'fatbuildrctl')())
  File "/usr/lib/python3/dist-packages/fatbuildr/cli/__init__.py", line 34, in run
    cls()
  File "/usr/lib/python3/dist-packages/fatbuildr/cli/fatbuildrctl.py", line 583, in __init__
    args.func(args)
  File "/usr/lib/python3/dist-packages/fatbuildr/cli/fatbuildrctl.py", line 1220, in _run_list
    running = self.connection.running()
  File "/usr/lib/python3/dist-packages/fatbuildr/protocols/http/client.py", line 38, in error_handler_wrapper
    return method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/fatbuildr/protocols/http/client.py", line 203, in running
    return JsonRunnableTask.load_from_json(json_task)
  File "/usr/lib/python3/dist-packages/fatbuildr/protocols/http/__init__.py", line 118, in load_from_json
    return super().load_from_json(fields, json)
  File "/usr/lib/python3/dist-packages/fatbuildr/protocols/http/__init__.py", line 68, in load_from_json
    wire_value = json[field.name]
KeyError: 'result'
```

**Comment by rezib** [comment]
This was due to service not being restart after upgrade, it was not a real bug.
