### ISSUE TITLE
Fix `fatbuildr.tasks.manager error while running task <id>: maximum recursion depth exceeded`

### ISSUE THREAD

**Issue by rezib** [rackslab/Fatbuildr#195]
Fix this error as reported in `fatbuildrd` logs:

```
fatbuildrd[406734]: worker-default: [INFO] fatbuildr.builds Running build 2eb06164-09d9-47dc-8139-17d86327fb53
fatbuildrd[406734]: worker-default: [INFO] fatbuildr.builds Extracting tarball /run/fatbuildr/e2zjmq90/fatbuildr-artifact.tar.xz in destination /var/lib/fatbuildr/workspaces/default/2eb06164-09d9-47dc-8139-17d86327>
fatbuildrd[406734]: worker-default: [DEBUG] fatbuildr.builds Removing build input tarball /run/fatbuildr/e2zjmq90/fatbuildr-artifact.tar.xz
fatbuildrd[406734]: worker-default: [DEBUG] fatbuildr.artifact Loading artifact definitions from /var/lib/fatbuildr/workspaces/default/2eb06164-09d9-47dc-8139-17d86327fb53/artifact.yml
fatbuildrd[406734]: worker-default: [INFO] fatbuildr.builds Using provided source archive /var/lib/fatbuildr/workspaces/default/2eb06164-09d9-47dc-8139-17d86327fb53/firehpc-1.2.0a1.dev49.tar.xz
fatbuildrd[406734]: worker-default: [DEBUG] fatbuildr.builds Artifact main version extracted from source tarball name:  1.2.0a1.dev49
fatbuildrd[406734]: worker-default: [DEBUG] fatbuildr.builds Removing build submission temporary files directory /run/fatbuildr/e2zjmq90
fatbuildrd[406734]: worker-default: [INFO] fatbuildr.builds Using artifact source archive from cache /var/cache/fatbuildr/default/firehpc/v0.0.1.tar.gz
fatbuildrd[406734]: worker-default: [DEBUG] fatbuildr.utils Extracting main source archive /var/lib/fatbuildr/workspaces/default/2eb06164-09d9-47dc-8139-17d86327fb53/firehpc-1.2.0a1.dev49.tar.xz in /var/lib/fatbuil>
fatbuildrd[406734]: worker-default: [DEBUG] fatbuildr.utils Extracting supplementary source archive /var/cache/fatbuildr/default/firehpc/v0.0.1.tar.gz in /var/lib/fatbuildr/workspaces/default/2eb06164-09d9-47dc-813>
fatbuildrd[406734]: worker-default: [INFO] fatbuildr.archive skipping extraction of file ansible-connection-machinectl-0.0.1 due to stripping
fatbuildrd[406734]: worker-default: [ERROR] fatbuildr.tasks.manager error while running task 2eb06164-09d9-47dc-8139-17d86327fb53: maximum recursion depth exceeded
fatbuildrd[406734]: worker-default: [INFO] fatbuildr.tasks.manager Task failed
```

**Comment by rezib** [comment]
I captured a stack of the exception:

```
fatbuildrd[412946]: Traceback (most recent call last):
fatbuildrd[412946]:   File "/usr/lib/python3/dist-packages/fatbuildr/tasks/manager.py", line 210, in run
fatbuildrd[412946]:     task.run()
fatbuildrd[412946]:   File "/usr/lib/python3/dist-packages/fatbuildr/builds/__init__.py", line 236, in run
fatbuildrd[412946]:     self.prepare()
fatbuildrd[412946]:   File "/usr/lib/python3/dist-packages/fatbuildr/builds/__init__.py", line 361, in prepare
fatbuildrd[412946]:     self.supplementary_archives_symlinks_patch()
fatbuildrd[412946]:   File "/usr/lib/python3/dist-packages/fatbuildr/builds/__init__.py", line 475, in supplementary_archives_symlinks_patch
fatbuildrd[412946]:     (upstream_dir, archive_subdir, git) = self._prepare_git_build_tree()
fatbuildrd[412946]:                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fatbuildrd[412946]:   File "/usr/lib/python3/dist-packages/fatbuildr/builds/__init__.py", line 444, in _prepare_git_build_tree
fatbuildrd[412946]:     if not self.patches_dir.empty:
fatbuildrd[412946]:            ^^^^^^^^^^^^^^^^^^^^^^
fatbuildrd[412946]:   File "/usr/lib/python3/dist-packages/fatbuildr/git.py", line 94, in empty
fatbuildrd[412946]:     not self.generic_subdir.exists()
fatbuildrd[412946]:         ^^^^^^^^^^^^^^^^^^^
fatbuildrd[412946]:   File "/usr/lib/python3.12/functools.py", line 995, in __get__
fatbuildrd[412946]:     val = self.func(instance)
fatbuildrd[412946]:           ^^^^^^^^^^^^^^^^^^^
fatbuildrd[412946]:   File "/usr/lib/python3/dist-packages/fatbuildr/git.py", line 80, in generic_subdir
fatbuildrd[412946]:     return PatchesSubdir(self, self.joinpath('generic'))
fatbuildrd[412946]:                                ^^^^^^^^^^^^^^^^^^^^^^^^
fatbuildrd[412946]:   File "/usr/lib/python3.12/pathlib.py", line 717, in joinpath
fatbuildrd[412946]:     return self.with_segments(self, *pathsegments)
fatbuildrd[412946]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fatbuildrd[412946]:   File "/usr/lib/python3.12/pathlib.py", line 385, in with_segments
fatbuildrd[412946]:     return type(self)(*pathsegments)
fatbuildrd[412946]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
fatbuildrd[412946]:   File "/usr/lib/python3/dist-packages/fatbuildr/git.py", line 74, in __new__
fatbuildrd[412946]:     obj = super().__new__(cls, path.joinpath('patches'))
fatbuildrd[412946]:                                ^^^^^^^^^^^^^^^^^^^^^^^^
fatbuildrd[412946]:   File "/usr/lib/python3.12/pathlib.py", line 717, in joinpath
fatbuildrd[412946]:     return self.with_segments(self, *pathsegments)
fatbuildrd[412946]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fatbuildrd[412946]:   File "/usr/lib/python3.12/pathlib.py", line 385, in with_segments
fatbuildrd[412946]:     return type(self)(*pathsegments)
fatbuildrd[412946]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
fatbuildrd[412946]:   File "/usr/lib/python3/dist-packages/fatbuildr/git.py", line 74, in __new__
fatbuildrd[412946]:     obj = super().__new__(cls, path.joinpath('patches'))
```

It seems Python 3.12 brings some changes in pathlib module that break our (weird) way to inherit from Path.
